### ISSUE TITLE
Option to hide the "See new Tweets" badge

### ISSUE THREAD

**Issue by Tomalak** [insin/control-panel-for-twitter#189]
The "See new Tweets" badge adds no useful information (there is a blue dot on the "Home" icon communicating the same thing), and it obstructs the timeline:

![image](https://user-images.githubusercontent.com/28300/212841901-b8a3340a-82d8-4293-a712-264ac4e74e16.png)

It would be a great candidate for removal.

**Comment by insin** [comment]
Notes:

```css
/* Desktop */
[data-testid="primaryColumn"] > div > div:first-child > div[style^="transform"],
/* Mobile */
[data-testid="TopNavBar"] + div[style^="transform"] {
  display: none;
}
```
