### ISSUE TITLE
Fix "Post" buttons

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-twitter#368]
WIP, need to adjust the size for the size preference in Display:

```css
[data-testid="SideNav_NewTweet_Button"] > div > span > div > div > span > span,
[data-testid="tweetButtonInline"] > div > span > span {
  font-size: 0;
}
[data-testid="SideNav_NewTweet_Button"] > div > span > div > div > span > span::after {
  content: "Tweet";
  font-size: 17px;
  vertical-align: -15%;
}
[data-testid="tweetButtonInline"] > div > span > span::after {
  content: "Tweet";
  font-size: 15px;
  vertical-align: -15%;
}
```
