### ISSUE TITLE
Add option to hide "You may be missing out on ads revenue sharing!" promos

### ISSUE THREAD

**Issue by SenselessVirus** [insin/control-panel-for-twitter#398]

**Comment by insin** [comment]
Will keep an eye out for these, the problem is you can't force them to appear to test removing them

**Comment by insin** [comment]
Finally got this - here's the markup so we can write something to try to hide it

![image](https://github.com/insin/control-panel-for-twitter/assets/226692/c5c18cf0-bed6-4b4b-8213-77b33d1fb1ae)

**Comment by insin** [comment]
```css
div[data-testid="cellInnerDiv"]:has(div[data-testid="inlinePrompt"]) {
  display: none;
}
```
