### ISSUE TITLE
Sticky section labels in the options popup

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-twitter#440]
```css
form,
form > section {
  background-color: inherit;
}

form > section.labelled > label,
form > section > label.checkbox {
  background-color: inherit;
  position: sticky;
  top: 0;
}
```

![](https://github.com/insin/control-panel-for-twitter/assets/226692/eb0aa788-9935-4626-9d6b-1c5653d1c681)
