### ISSUE TITLE
Twitter logo replacement is purple for some reason?

### ISSUE THREAD

**Issue by nokel** [insin/control-panel-for-twitter#466]
![image](https://github.com/insin/control-panel-for-twitter/assets/13248734/1fe71109-8e53-4fab-96e3-162fbcf643b4)

Not sure why it's like this as I don't have any other addons

**Comment by krisu5** [comment]
Here's workaround fix for [Stylus](https://github.com/openstyles/stylus#readme) addon meanwhile:

```css
@-moz-document domain("twitter.com") {
/* "Control Panel for Twitter": fix logo color */
svg path[d^="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16"] { fill: rgb(29 161 242) !important; }
}
```
