### ISSUE TITLE
Premium upsell after adding a bookmark

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-twitter#548]
The Add to Folder link is a Premium upsell

![image](https://github.com/insin/control-panel-for-twitter/assets/226692/e6488363-c6fb-461b-8514-d31ee90db59f)

**Comment by insin** [comment]
This is a CSS-only way hide the Add to Folder link on desktop and mobile, but will also hide any similar link in a toast with the same markup - are there more of these?

```css
div[data-testid="toast"] div[aria-hidden="true"]:has(> div[role="button"]) {
  display: none;
}
```

The alternative is to detect the appearance of toasts and check specifically for the "Add to Folder" button text.

- desktop: appears as a child of `#layers`, which we're already observing
- mobile: appears as a child of `#layers > :first-child`, which contains the other overlay items for the mobile layout
