### ISSUE TITLE
Request: Make user profile navigation floating and stick to top

### ISSUE THREAD

**Issue by BD9Max** [insin/control-panel-for-twitter#75]
Request: Make user profile navigation floating and stick to top

So that when u scroll down down down the horizontal navigation stays on top of the page :)

![image](https://user-images.githubusercontent.com/82726385/137910895-e82f2f3b-43b8-4b2c-bcd4-571c9793556d.png)

This was possible with the old interface by an extensions

**Comment by insin** [comment]
Looks like we can do this entirely in CSS, just need to make it handle the different theme variants and the current size of the top header in the user's browser:

```css
[data-testid="primaryColumn"] nav[role="navigation"] {
  position: sticky;
  top: 53px;
  background-color: rgba(255, 255, 255, 0.97);
  z-index: 1;
}
```

![firefox_8n51wkwfjr](https://user-images.githubusercontent.com/226692/151361205-264650dc-2ed0-4660-a883-17a935671a48.gif)
